# Exploración inicial de datos

## 📚 Importación de las librerias

In [1]:
from pathlib import Path

import numpy as np
import pandas as pd
import pyarrow as pa

## 💾 Carga de los datos

In [2]:
# data directory path
DATA_DIR = Path.cwd().resolve().parents[0] / "data"

mora_df = pd.read_excel(DATA_DIR / "01_raw/03-mora.xlsx")

## 📊 Descripción de los datos

In [3]:
mora_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 3272 entries, 0 to 3271
Data columns (total 16 columns):
 #   Column                                Non-Null Count  Dtype
---  ------                                --------------  -----
 0   Período                               3272 non-null   datetime64[us]
 1   CUIT                                  3272 non-null   int64
 2   SGR                                   3272 non-null   str
 3   Monto_de_MORA                         3272 non-null   float64
 4   Monto_de_MORA_sin_DEUDA_PROPORCIONAL  3265 non-null   float64
 5   Cantidad_de_GARANTÍAS_en_MORA         3272 non-null   int64
 6   Cantidad_de_PYMES_en_MORA             3272 non-null   int64
 7   %_PRÉSTAMO_BANCARIO                   3272 non-null   str
 8   %_CHEQUE_de_PAGO_DIFERIDO             3272 non-null   str
 9   %_PAGARÉ_BURSÁTIL                     3272 non-null   str
 10  %_OTRAS                               3272 non-null   str
 11  %_MENOR_a_31_DÍAS                     3272 non-null   str
 12  %_MENOR_a_90_DÍAS                     3272 non-null   str
 13  %_MENOR_a_180_DÍAS                    3272 non-null   str
 14  %_MENOR_a_365_DÍAS                    3272 non-null   str
 15  %_MAYOR_a_365_DÍAS                    3272 non-null   str
dtypes: datetime64[us](1), float64(2), int64(3), str(10)
memory usage: 597.8 KB

In [4]:
mora_df.sample(10)

,Período,CUIT,SGR,Monto_de_MORA,Monto_de_MORA_sin_DEUDA_PROPORCIONAL,Cantidad_de_GARANTÍAS_en_MORA,Cantidad_de_PYMES_en_MORA,%_PRÉSTAMO_BANCARIO,%_CHEQUE_de_PAGO_DIFERIDO,%_PAGARÉ_BURSÁTIL,%_OTRAS,%_MENOR_a_31_DÍAS,%_MENOR_a_90_DÍAS,%_MENOR_a_180_DÍAS,%_MENOR_a_365_DÍAS,%_MAYOR_a_365_DÍAS
2491,2025-03-01,30708255102,AGROAVAL S.G.R.,2.895462e+06,2.809390e+05,5,5,72.5%,0.0%,0.0%,27.5%,4.2%,13.4%,3.0%,2.1%,77.3%
1825,2023-12-01,30697281106,AVALUAR S.G.R.,1.295326e+08,9.039107e+07,99,19,4.0%,37.1%,58.9%,0.1%,0.0%,2.6%,22.3%,63.9%,11.2%
1774,2023-11-01,30708802979,AVAL FEDERAL S.G.R.,1.179143e+08,9.341835e+07,40,17,93.1%,6.8%,0.0%,0.1%,4.3%,24.7%,13.2%,46.0%,11.8%
943,2022-01-01,30708609915,GARANTIAS BIND S.G.R.,7.768799e+07,1.913411e+07,79,18,38.8%,12.6%,7.2%,41.3%,0.7%,0.2%,1.8%,16.6%,80.8%
738,2021-08-01,30697281106,AVALUAR S.G.R.,1.560702e+07,7.935959e+06,76,11,0.0%,89.4%,10.6%,0.0%,0.0%,8.3%,0.0%,29.2%,62.5%
2035,2024-04-01,33708194919,SOLIDUM S.G.R.,1.015199e+07,2.424759e+06,39,4,0.0%,73.1%,26.7%,0.2%,0.0%,0.0%,0.1%,0.1%,99.8%
2020,2024-04-01,33709146519,FONDO ESPECIFICO DE RIESGO FIDUCIARIO PROVINCI...,1.285096e+07,1.285096e+07,6,6,100.0%,0.0%,0.0%,0.0%,36.9%,17.7%,19.4%,17.3%,8.7%
53,2020-02-01,30711015805,CRECER S.G.R.,3.893195e+07,1.639477e+07,162,30,4.4%,72.0%,20.4%,3.2%,2.4%,0.7%,11.3%,27.8%,57.8%
1842,2023-12-01,30715046012,INTEGRA PYMES S.G.R.,1.479030e+08,1.084054e+08,73,18,5.0%,38.8%,56.2%,0.1%,0.6%,18.7%,32.3%,42.5%,5.9%
1429,2023-03-01,30708255102,AGROAVAL S.G.R.,3.565423e+06,0.000000e+00,2,2,58.9%,41.1%,0.0%,0.0%,0.0%,0.0%,0.0%,0.0%,100.0%

### Valores nulos

No presenta valores nulos.

## Variables

| Título de la columna | Descripción | Tipo de Variable |
| :--- | :--- | :--- |
| Período | Mes y año informado. | Cualitativa Ordinal / Temporal (Fecha) |
| CUIT | CUIT de la SGR. | Cualitativa Nominal (Identificador) |
| SGR | Razón Social de la SGR. | Cualitativa Nominal |
| Monto_de_MORA | Mora y/o incobrabilidad de garantías otorgadas, por SGR y por mes, según normas vigentes sobre "Previsiones Mínimas por Riesgo de Incobrabilidad" del BCRA. | Cuantitativa Continua |
| Monto_de_MORA_sin_DEUDA_PROPORCIONAL | Monto de la mora y/o incobrabilidad de garantías otorgadas menos deuda proporcional asignada, por SGR y por mes, donde la "Deuda proporcional asignada": incobrables e importes trasladados al pasivo. | Cuantitativa Continua |
| Cantidad_de_GARANTÍAS_en_MORA | Cantidad de garantías honradas en mora, por SGR y por mes. | Cuantitativa Discreta |
| Cantidad_de_PYMES_en_MORA | Cantidad de MiPyMEs en mora, por SGR y por mes. | Cuantitativa Discreta |
| %_PRÉSTAMO_BANCARIO | Porcentaje de garantías honradas para PRÉSTAMO BANCARIO en mora, por SGR y por mes, con respecto al total de garantías en mora por cada SGR en el mismo período. | Cuantitativa Continua (Proporción / Ratio) |
| %_PAGARÉ_BURSÁTIL | Porcentaje de garantías honradas para PAGARÉ BURSÁTIL en mora, por SGR y por mes, con respecto al total de garantías en mora por cada SGR en el mismo período. | Cuantitativa Continua (Proporción / Ratio) |
| %_CHEQUE_de_PAGO_DIFERIDO | Porcentaje de garantías honradas para CHEQUE DE PAGO DIFERIDO en mora, por SGR y por mes, con respecto al total de garantías en mora por cada SGR en el mismo período. | Cuantitativa Continua (Proporción / Ratio) |
| %_OTRAS | Porcentaje de OTRAS garantías honradas en mora, por SGR y por mes, con respecto al total de garantías en mora por cada SGR en el mismo período. | Cuantitativa Continua (Proporción / Ratio) |
| %_MENOR_a_31_DÍAS | Porcentaje de garantías honradas con mora menor a 31 días, por SGR y por mes, respecto al total de garantías en mora por SGR para mes informado, según normativa vigente BCRA. | Cuantitativa Continua (Proporción / Ratio) |
| %_MENOR_a_90_DÍAS | Porcentaje de garantías honradas con mora menor a 90 días, por SGR y por mes, respecto al total de garantías en mora por SGR para mes informado, según normativa vigente BCRA. | Cuantitativa Continua (Proporción / Ratio) |
| %_MENOR_a_180_DÍAS | Porcentaje de garantías honradas con mora menor a 180 días, por SGR y por mes, respecto al total de garantías en mora por SGR para mes informado, según normativa vigente BCRA. | Cuantitativa Continua (Proporción / Ratio) |
| %_MENOR_a_365_DÍAS | Porcentaje de garantías honradas con mora menor a 365 días, por SGR y por mes, respecto al total de garantías en mora por SGR para mes informado, según normativa vigente BCRA. | Cuantitativa Continua (Proporción / Ratio) |
| %_MAYOR_a_365_DÍAS | Porcentaje de garantías honradas con mora mayor a 365 días, por SGR y por mes, respecto al total de garantías en mora por SGR para mes informado, según normativa vigente BCRA. | Cuantitativa Continua (Proporción / Ratio) |

## Conversión de tipos

In [5]:
columnas_porcentuales = [
    '%_PRÉSTAMO_BANCARIO',
    '%_PAGARÉ_BURSÁTIL',
    '%_CHEQUE_de_PAGO_DIFERIDO',
    '%_OTRAS',
    '%_MENOR_a_31_DÍAS',
    '%_MENOR_a_90_DÍAS',
    '%_MENOR_a_180_DÍAS',
    '%_MENOR_a_365_DÍAS',
    '%_MAYOR_a_365_DÍAS'
]

for columna in columnas_porcentuales:
    mora_df[columna] = (
        mora_df[columna]
        .astype(str)
        .str.replace('%', '', regex=False)
        .str.replace(',', '.', regex=False)
        .str.strip()
    )
    mora_df[columna] = pd.to_numeric(mora_df[columna], errors='coerce')

In [6]:
mora_df.info()
mora_df.sample(5)

<class 'pandas.DataFrame'>
RangeIndex: 3272 entries, 0 to 3271
Data columns (total 16 columns):
 #   Column                                Non-Null Count  Dtype
---  ------                                --------------  -----
 0   Período                               3272 non-null   datetime64[us]
 1   CUIT                                  3272 non-null   int64
 2   SGR                                   3272 non-null   str
 3   Monto_de_MORA                         3272 non-null   float64
 4   Monto_de_MORA_sin_DEUDA_PROPORCIONAL  3265 non-null   float64
 5   Cantidad_de_GARANTÍAS_en_MORA         3272 non-null   int64
 6   Cantidad_de_PYMES_en_MORA             3272 non-null   int64
 7   %_PRÉSTAMO_BANCARIO                   3272 non-null   float64
 8   %_CHEQUE_de_PAGO_DIFERIDO             3272 non-null   float64
 9   %_PAGARÉ_BURSÁTIL                     3272 non-null   float64
 10  %_OTRAS                               3272 non-null   float64
 11  %_MENOR_a_31_DÍAS                     3272 non-null   float64
 12  %_MENOR_a_90_DÍAS                     3272 non-null   float64
 13  %_MENOR_a_180_DÍAS                    3272 non-null   float64
 14  %_MENOR_a_365_DÍAS                    3272 non-null   float64
 15  %_MAYOR_a_365_DÍAS                    3272 non-null   float64
dtypes: datetime64[us](1), float64(11), int64(3), str(1)
memory usage: 468.0 KB

,Período,CUIT,SGR,Monto_de_MORA,Monto_de_MORA_sin_DEUDA_PROPORCIONAL,Cantidad_de_GARANTÍAS_en_MORA,Cantidad_de_PYMES_en_MORA,%_PRÉSTAMO_BANCARIO,%_CHEQUE_de_PAGO_DIFERIDO,%_PAGARÉ_BURSÁTIL,%_OTRAS,%_MENOR_a_31_DÍAS,%_MENOR_a_90_DÍAS,%_MENOR_a_180_DÍAS,%_MENOR_a_365_DÍAS,%_MAYOR_a_365_DÍAS
2974,2026-01-01,33708194919,SOLIDUM S.G.R.,3.810689e+08,2.202788e+08,21,8,2.3,1.4,96.2,0.1,1.5,2.2,96.2,0.0,0.0
2188,2024-08-01,30716480387,CONAVAL S.G.R.,2.843843e+07,1.563697e+07,7,3,0.0,14.1,85.9,0.0,0.0,0.0,0.0,14.1,85.9
2768,2025-09-01,30715060953,AVAL AR S.G.R.,7.664096e+08,6.524683e+08,127,23,24.3,58.7,16.8,0.1,8.5,19.8,37.8,32.1,1.8
734,2021-08-01,30714824631,AVAL FERTIL S.G.R.,6.793252e+07,2.429570e+07,49,12,0.5,29.0,70.5,0.0,0.0,24.5,0.0,0.0,75.5
2081,2024-05-01,30716644622,TREND S.G.R.,2.217051e+07,1.820919e+07,4,4,61.6,0.0,37.7,0.7,0.1,0.0,48.8,50.9,0.2

## Guardar dataset formateado en local

In [7]:
mora_df.to_parquet(
    DATA_DIR / "02_intermediate/mora_tipado.parquet", index=False
)